INSERT INTO POSTS (USER_ID, BODY)
VALUES (4,"New post from task 16.5.");

UPDATE POSTS 
SET BODY="To delete"
WHERE (USER_ID=4 AND ID=7);

DELETE FROM POSTS 
WHERE (USER_ID=4 AND ID=7);

COMMIT;

SELECT * FROM POSTS;