CREATE TABLE ISSUESLISTS
(
ID SERIAL PRIMARY KEY,
NAME VARCHAR(100)
);

CREATE TABLE ISSUES
(
ID SERIAL PRIMARY KEY,
ISSUESLIST_ID BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (ISSUESLIST_ID) REFERENCES ISSUESLISTS(ID),
SUMMARY VARCHAR(2000),
DESCRIPTION VARCHAR(2000),
USER_ID_ASSIGNEDTO BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (USER_ID_ASSIGNEDTO) REFERENCES USERS(ID)
);

INSERT INTO ISSUESLISTS (NAME)
VALUES ("ToDo");

INSERT INTO ISSUESLISTS (NAME)
VALUES ("In progress");

INSERT INTO ISSUESLISTS (NAME)
VALUES ("Done");

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "work", "contact with John", 1);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "work", "meeting", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "training", "gym", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "home", "shopping", 4);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (1, "home", "cleaning bathroom", 5);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "work", "benefits", 1);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "work", "check project", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "training", "training schedule", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "home", "completing the child's homework", 4);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (2, "home", "cleaning kitchen", 5);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "work", "project finished", 1);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "work", "initial assumptions", 2);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "training", "meeting with coach", 3);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "home", "homework in math with child", 4);

INSERT INTO ISSUES (ISSUESLIST_ID, SUMMARY, DESCRIPTION, USER_ID_ASSIGNEDTO)
VALUES (3, "home", "bedroom cleaned", 5);

COMMIT;

SELECT * FROM ISSUES;