SELECT I.SUMMARY AS TASKS_LIST, L.NAME AS NAME_OF_TASKS_LIST
FROM ISSUES I JOIN ISSUESLISTS L ON I.ISSUESLIST_ID=L.ID;

SELECT I.SUMMARY AS TASKS_LIST, U.FIRSTNAME AS FIRSTNAME_OF_USER, U.LASTNAME AS LASTNAME_OF_USER
FROM ISSUES I JOIN USERS U ON I.ISSUESLIST_ID=U.ID;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS NUMBER_OF_TASKS
FROM USERS U JOIN ISSUES I ON U.ID=I.USER_ID_ASSIGNEDTO
GROUP BY USER_ID_ASSIGNEDTO;